In [1]:
from torch.nn import Conv2d

In [2]:
?xrange()

Object `xrange` not found.


In [1]:
import numpy as np

In [11]:
tarr = np.array([[1001,1002],[3,4]])
tarr

array([[1001, 1002],
       [   3,    4]])

In [3]:
a = np.exp(tarr)
a

array([[        inf,         inf],
       [20.08553692, 54.59815003]])

In [13]:
b = np.max(tarr,axis=1)
b

array([1002,    4])

In [22]:
norm_tarr = np.transpose(np.subtract(np.transpose(tarr),b))
norm_tarr

array([[-1,  0],
       [-1,  0]])

In [23]:
c = np.exp(norm_tarr)
c

array([[0.36787944, 1.        ],
       [0.36787944, 1.        ]])

In [25]:
c/np.sum(c, axis=1)

array([[0.26894142, 0.73105858],
       [0.26894142, 0.73105858]])

In [6]:
N = 20
dimensions = [10, 5, 10]
data = np.random.randn(N, dimensions[0])   # each row will be a datum
labels = np.zeros((N, dimensions[2]))
for i in range(N):
    labels[i, np.random.randint(0,dimensions[2]-1)] = 1

params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
    dimensions[1] + 1) * dimensions[2], )
print('data:')
print(data)
print('------')
print('label:')
print(labels)
print('------')
print('params:')
print(params)

#neruals implement
ofs = 0
W1= np.reshape(params[ofs:ofs+ Dx * H], (Dx, H))
ofs += Dx * H
b1 = np.reshape(params[ofs:ofs + H], (1, H))
ofs += H
W2 = np.reshape(params[ofs:ofs + H * Dy], (H, Dy))
ofs += H * Dy
b2 = np.reshape(params[ofs:ofs + Dy], (1, Dy))
print('w1:')
print(W1)
print('------')
print('w2:')
print(W2)

data:
[[ 1.97732065  2.45128849 -1.42588318 -0.91960725  1.06324018  0.85788457
   0.10001571 -0.39735998 -0.22493615  0.4405186 ]
 [-0.47476099 -0.0605179   1.07261479  0.33009152 -1.81151736 -1.49495499
  -0.03869143  1.05028854 -1.80937501 -2.42183164]
 [ 0.2504126  -0.4808754  -1.42247497  0.86627348  0.46013826  1.6428274
   1.52483961 -0.07309406 -0.50841876  0.14208075]
 [ 0.91462658 -0.18856526 -0.74291082  0.4126448  -2.38424515 -0.13045274
  -1.67470919 -0.4797349   1.2674691  -0.29375387]
 [ 0.89017524  0.34165861 -0.91059588  0.68492391  0.03700612 -0.0138411
  -0.8197134  -0.38627667 -0.23196893  1.54868783]
 [-0.69257082 -0.01006812 -1.15049919 -0.41129921  1.47735502 -0.6019625
  -0.55149261  0.52134916 -0.65283033 -0.17571575]
 [-1.30844258  0.68348074 -1.61304669 -0.46161365  0.41828873  1.30925685
  -1.6433895   0.37083051 -0.06579537 -0.38806595]
 [-0.06118826  0.10276262  1.19686411 -0.11383792  0.9698485   0.69559773
   0.82394317  1.58034347 -0.2771151   1.5387156

NameError: name 'Dx' is not defined

In [8]:
np.log(labels)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[-inf, -inf, -inf, -inf,   0., -inf, -inf, -inf, -inf, -inf],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0., -inf],
       [-inf, -inf, -inf,   0., -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf,   0., -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf,   0., -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0., -inf],
       [-inf,   0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf,   0., -inf, -inf],
       [-inf, -inf, -inf, -inf,   0., -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf,   0., -inf, -inf],
       [-inf, -inf,   0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf, -inf, -inf, -inf,   0., -inf, -inf],
       [-inf, -inf, -inf, -inf,   

In [11]:
len(data.shape)

2

In [12]:
fx, grad = f(x)

NameError: name 'f' is not defined

In [ ]:
labels[labels]