In [1]:
import numpy as np

In [3]:
rand_a = np.random.randn(3, 4)
# 随机生成3 * 4矩阵
print(rand_a)

[[-0.67300295 -1.73540305 -0.87559276  1.33239164]
 [ 0.21872773 -0.77032951  0.33818333  0.95399361]
 [-0.36021481  2.01615782 -0.29977132  0.4364348 ]]


In [11]:
denom = np.apply_along_axis(lambda x: np.sqrt(x.T.dot(x)), 1, rand_a)
# apply_along_axis方法
print(denom)

[2.45081351 1.2906282  2.11541609]


In [12]:
print(np.shape(denom))

(3,)


In [7]:
#assignment1 q3 word2vec  denom[:, None]数组切片用法演示
denom[:, None]

array([[2.45081351],
       [1.2906282 ],
       [2.11541609]])

In [10]:
print(np.shape(denom[:, None]))

(3, 1)


In [13]:
rand_a[:, None]

array([[[-0.67300295, -1.73540305, -0.87559276,  1.33239164]],

       [[ 0.21872773, -0.77032951,  0.33818333,  0.95399361]],

       [[-0.36021481,  2.01615782, -0.29977132,  0.4364348 ]]])

In [14]:
np.shape(rand_a[:, None])

(3, 1, 4)